/**
 * Permissões adicionais alinhadas ao catálogo de módulos do `fase_1.md`.
 * Mantidas separadas para não inflar demais `permissions.ts`.
 */
export const FASE1_EXTRA_PERMISSIONS = [
  {
    key: 'tab.operacional.visao_geral.view',
    label: 'Operacional: Visão geral',
    description: 'Dashboard / visão geral do módulo operacional.',
    group: 'ABA',
    section: 'operacional',
  },
  {
    key: 'tab.operacional.rastreio.view',
    label: 'Operacional: Rastreio',
    description: 'Rastreio operacional de mercadorias.',
    group: 'ABA',
    section: 'operacional',
  },
  {
    key: 'module.manifestos.view',
    label: 'Módulo Manifestos e CTEs',
    description: 'Acessar rotas /app/manifestos (fiscal, MDF-e, monitor).',
    group: 'MODULO',
    section: 'operacional',
  },
  {
    key: 'module.clientes.view',
    label: 'Módulo Clientes e tabelas de preço',
    description: 'Acessar rotas /app/clientes.',
    group: 'MODULO',
    section: 'comercial',
  },
  {
    key: 'module.patrimonio.view',
    label: 'Módulo Patrimônio',
    description: 'Acessar rotas /app/patrimonio.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.financeiro.view',
    label: 'Módulo Financeiro',
    description: 'Acessar rotas /app/financeiro.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.fiscal.view',
    label: 'Módulo Fiscal',
    description: 'Acessar rotas /app/fiscal.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.rh.view',
    label: 'Módulo DP / RH',
    description: 'Acessar rotas /app/rh.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.compras.view',
    label: 'Módulo Compras e suprimentos',
    description: 'Acessar rotas /app/compras.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.juridico.view',
    label: 'Módulo Jurídico / Compliance',
    description: 'Acessar rotas /app/juridico.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.gerencial.view',
    label: 'Módulo Gerencial / BI',
    description: 'Acessar rotas /app/gerencial.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.gerencial.comissoes_holerite',
    label: 'Gerencial: holerite de comissões',
    description:
      'Imprimir / consultar holerite de comissões (linhas da base analítica). Pode ser combinada com visão restrita no futuro.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.setor.comercial.view',
    label: 'Gerencial: setor Comercial (BI)',
    description: 'Acessar o setor Comercial em Metas & performance / comissões / funil / sprint.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.setor.financeiro.view',
    label: 'Gerencial: setor Financeiro',
    description: 'Acessar o setor Financeiro no hub gerencial (conteúdo em evolução).',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.setor.operacao.view',
    label: 'Gerencial: setor Operação',
    description: 'Acessar o setor Operação no hub gerencial (conteúdo em evolução).',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.comissoes.view',
    label: 'Gerencial: Comissões (BI)',
    description: 'Painel de comissões e bases analíticas do schema bi.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.funil.view',
    label: 'Gerencial: Performance de vendas (funil)',
    description: 'Funil de cotações e performance comercial.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.sprint.view',
    label: 'Gerencial: Sprint & incentivos',
    description: 'Campanha mensal de metas e incentivos por vendedora.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.metas.view',
    label: 'Gerencial: Metas & performance',
    description: 'Metas por agência e projeção de faturamento.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.carteira_renovacao.view',
    label: 'Gerencial: Carteira & renovação',
    description: 'Central de tabelas combinadas: renovação, risco, recuperação e priorização de clientes.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.fluxo.view',
    label: 'Gerencial: Monitor de fluxo',
    description: 'Painel logístico de emissões, recebimentos e equilíbrio da rede por agência.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.taxas.view',
    label: 'Gerencial: Gestão de taxas',
    description: 'Painel de serviços extras: receita, penetração, ticket médio e oportunidade por agência.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.360.cockpit.view',
    label: 'Gerencial: Comercial 360 — Cockpit',
    description: 'Priorização de oportunidades, contato rápido e drill por cliente (base 360).',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.360.executiva.view',
    label: 'Gerencial: Comercial 360 — Central executiva',
    description: 'KPIs, evolução mensal e resumos por contrato, documento, categoria e status.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.360.risco.view',
    label: 'Gerencial: Comercial 360 — Risco e ciclo',
    description: 'Distribuição por status de atividade e foco em queda / churn.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.360.gap.view',
    label: 'Gerencial: Comercial 360 — Potencial e GAP',
    description: 'Faturamento vs potencial, GAP por categoria e lista priorizada.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'tab.gerencial.360.radar.view',
    label: 'Gerencial: Comercial 360 — Radar de prospecção',
    description: 'Segmentos CIF, sem contrato com faturamento e exploração por documento.',
    group: 'ABA',
    section: 'administracao',
  },
  {
    key: 'module.auditoria.view',
    label: 'Módulo Auditoria e controle',
    description: 'Acessar rotas /app/auditoria (logs, trilhas).',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'portal.gestor.view',
    label: 'Portal do gestor (área)',
    description: 'Acessar o portal do gestor em /gestor.',
    group: 'MODULO',
    section: 'portal',
  },
  {
    key: 'portal.gestor.equipe.view',
    label: 'Portal gestor: Minha equipe',
    description: 'Listar colaboradores da equipe.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.escalas.view',
    label: 'Portal gestor: Escalas da equipe',
    description: 'Visualizar e editar escalas do time.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.aprovacoes.view',
    label: 'Portal gestor: Aprovações',
    description: 'Fila de aprovações do setor.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.pendencias_setor.view',
    label: 'Portal gestor: Pendências do setor',
    description: 'Pendências operacionais do setor.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.comunicados_setor.view',
    label: 'Portal gestor: Comunicados do setor',
    description: 'Comunicados direcionados ao setor.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.indicadores.view',
    label: 'Portal gestor: Indicadores rápidos',
    description: 'KPIs resumidos da equipe.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.solicitacoes_time.view',
    label: 'Portal gestor: Solicitações do time',
    description: 'Solicitações internas abertas pela equipe.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.content.manage',
    label: 'Portal gestor: CMS (banners, campanhas, notícias)',
    description: 'Cadastrar e publicar conteúdo dinâmico do portal (content_items + arquivos SharePoint).',
    group: 'ACAO',
    section: 'portal',
  },
  {
    key: 'portal.colaborador.editor',
    label: 'Portal: editor de conteúdo (comunicação)',
    description:
      'Publicar e trocar banners, comunicados, treinamentos, documentos e agenda pelo portal (/portal-edicao), sem precisar da área Gestor nem do SharePoint manual.',
    group: 'ACAO',
    section: 'portal',
  },
  {
    key: 'scope.admin.setor',
    label: 'Escopo: dados do próprio setor (gestão)',
    description: 'Limita indicadores e listas do portal gestor ao setor do usuário.',
    group: 'ESCOPO',
    section: 'escopos',
  },
] as const;
