/**
 * Permissões adicionais alinhadas ao catálogo de módulos do `fase_1.md`.
 * Mantidas separadas para não inflar demais `permissions.ts`.
 */
export const FASE1_EXTRA_PERMISSIONS = [
  {
    key: 'tab.operacional.visao_geral.view',
    label: 'Operacional: Visão geral',
    description: 'Dashboard / visão geral do módulo operacional.',
    group: 'ABA',
    section: 'operacional',
  },
  {
    key: 'tab.operacional.rastreio.view',
    label: 'Operacional: Rastreio',
    description: 'Rastreio operacional de mercadorias.',
    group: 'ABA',
    section: 'operacional',
  },
  {
    key: 'module.manifestos.view',
    label: 'Módulo Manifestos e CTEs',
    description: 'Acessar rotas /app/manifestos (fiscal, MDF-e, monitor).',
    group: 'MODULO',
    section: 'operacional',
  },
  {
    key: 'module.clientes.view',
    label: 'Módulo Clientes e tabelas de preço',
    description: 'Acessar rotas /app/clientes.',
    group: 'MODULO',
    section: 'comercial',
  },
  {
    key: 'module.patrimonio.view',
    label: 'Módulo Patrimônio',
    description: 'Acessar rotas /app/patrimonio.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.financeiro.view',
    label: 'Módulo Financeiro',
    description: 'Acessar rotas /app/financeiro.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.fiscal.view',
    label: 'Módulo Fiscal',
    description: 'Acessar rotas /app/fiscal.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.rh.view',
    label: 'Módulo DP / RH',
    description: 'Acessar rotas /app/rh.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.compras.view',
    label: 'Módulo Compras e suprimentos',
    description: 'Acessar rotas /app/compras.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.juridico.view',
    label: 'Módulo Jurídico / Compliance',
    description: 'Acessar rotas /app/juridico.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.gerencial.view',
    label: 'Módulo Gerencial / BI',
    description: 'Acessar rotas /app/gerencial.',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'module.auditoria.view',
    label: 'Módulo Auditoria e controle',
    description: 'Acessar rotas /app/auditoria (logs, trilhas).',
    group: 'MODULO',
    section: 'administracao',
  },
  {
    key: 'portal.gestor.view',
    label: 'Portal do gestor (área)',
    description: 'Acessar o portal do gestor em /gestor.',
    group: 'MODULO',
    section: 'portal',
  },
  {
    key: 'portal.gestor.equipe.view',
    label: 'Portal gestor: Minha equipe',
    description: 'Listar colaboradores da equipe.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.escalas.view',
    label: 'Portal gestor: Escalas da equipe',
    description: 'Visualizar e editar escalas do time.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.aprovacoes.view',
    label: 'Portal gestor: Aprovações',
    description: 'Fila de aprovações do setor.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.pendencias_setor.view',
    label: 'Portal gestor: Pendências do setor',
    description: 'Pendências operacionais do setor.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.comunicados_setor.view',
    label: 'Portal gestor: Comunicados do setor',
    description: 'Comunicados direcionados ao setor.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.indicadores.view',
    label: 'Portal gestor: Indicadores rápidos',
    description: 'KPIs resumidos da equipe.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'portal.gestor.solicitacoes_time.view',
    label: 'Portal gestor: Solicitações do time',
    description: 'Solicitações internas abertas pela equipe.',
    group: 'ABA',
    section: 'portal',
  },
  {
    key: 'scope.admin.setor',
    label: 'Escopo: dados do próprio setor (gestão)',
    description: 'Limita indicadores e listas do portal gestor ao setor do usuário.',
    group: 'ESCOPO',
    section: 'escopos',
  },
] as const;
